
package com.example.demo.mypractice;

import java.util.ArrayList;
import java.util.HashMap;

public class StringCharOcurrence {

	public static void main(String[] args) {
		
		//ocurrenceOfChars1("Arindam Arindam Arindam");
		ocurrenceOfChars1("zzzzhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqzzzzhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqzzzzhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaq");
		System.out.println("--------------------------------");
		ocurrenceOfChars2("zzzzhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqzzzzhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqzzzzhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaqhdgbnwteofpjvaqnvmertodfwmitrnvdlpotrweqnzcxsnmkajlsdireghcqutwertyuioplkjhgfdaszxcvbnmqazwsxedcrfvtgbyhnujmikolpplmoknijbuhvygctfxrdzeswaq");
		
	}
	
	
	static void ocurrenceOfChars1(String s) {
		HashMap<Character, Integer> charCountMap = new HashMap<>();
		for(int i=0; i<s.length(); i++) {
		
			if(s.charAt(i) != ' ')		//ignoring spaces 
			{
				if(charCountMap.containsKey(s.charAt(i))) {
					int count = charCountMap.get(s.charAt(i)) + 1;
					charCountMap.put(s.charAt(i), count);
				}else {
					charCountMap.put(s.charAt(i), 1);
				}
			}	
		}
		
		System.out.println(charCountMap);
	}
	
	
	static void ocurrenceOfChars2(String s) {
		ArrayList<Character> list = new ArrayList<>();
		for(int i=0; i<s.length(); i++) {
			if(s.charAt(i) != ' ') {
				if( !list.contains(s.charAt(i) )){
					list.add(s.charAt(i));
					int count = 1 ;
					for(int j=i+1; j<s.length(); j++) {
						if(s.charAt(i) == s.charAt(j)) {
							count ++;	
						}
					}
				
					System.out.print(s.charAt(i) +"="+count+", ");
				}
			}
		}
		
	}
	
}






